document.write("<p>Informe de la asignatura: ");
document.write(subject.name);
document.write("</p>");
document.write("<p>Titulación: ");
document.write(subject.degree);
document.write("</p>");
document.write("<p>Centro: ");
document.write(subject.school);
document.write("</p>");
document.write("<p>Universidad: ");
document.write(subject.university);
document.write("</p>");
document.write("<p>Curso actual: ");
document.write(subject.course);
document.write("</p>");
document.write("<p>Profesor: ");
document.write(subject.teacher);
document.write("</p>");
document.write("<p>Correo electrónico: ");
document.write(subject.email);
document.write("</p>");